#!/usr/bin/env bun
/**
 * Reads version from package.json and writes it to src/version.ts
 * Run before building: bun scripts/inject-version.ts
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

const packageJson = JSON.parse(readFileSync(join(rootDir, 'package.json'), 'utf-8'));
const version = packageJson.version;

const content = `// Auto-generated by scripts/inject-version.ts - DO NOT EDIT
export const VERSION = '${version}';
`;

writeFileSync(join(rootDir, 'src', 'version.ts'), content);
console.log(`Injected version ${version} into src/version.ts`);
